version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -U pip
            sudo pip install pytest coverage coveralls
            coverage run --source=pyconfiger -m pytest
            coverage html
            COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
      - store_artifacts:
          path: htmlcov
  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "  username = __token__" >> ~/.pypirc
            echo -e "  password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          command: |
            sudo pip install pytest build twine
            python -m pytest
            python -m build
            twine upload dist/*

workflows:
  version: 2
  test:
    jobs:
      - test
  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
